config/routes.rb
Rails.application.routes.draw do
  resources :habitations
  resources :hotels
  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/habitation.rb
class Habitation < ApplicationRecord
end

app/models/hotel.rb
class Hotel < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/habitations_controller.rb
class HabitationsController < ApplicationController
  before_action :set_habitation, only: %i[ show edit update destroy ]

  # GET /habitations or /habitations.json
  def index
    @habitations = Habitation.all
  end

  # GET /habitations/1 or /habitations/1.json
  def show
  end

  # GET /habitations/new
  def new
    @habitation = Habitation.new
  end

  # GET /habitations/1/edit
  def edit
  end

  # POST /habitations or /habitations.json
  def create
    @habitation = Habitation.new(habitation_params)

    respond_to do |format|
      if @habitation.save
        format.html { redirect_to habitation_url(@habitation), notice: "Habitation was successfully created." }
        format.json { render :show, status: :created, location: @habitation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @habitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /habitations/1 or /habitations/1.json
  def update
    respond_to do |format|
      if @habitation.update(habitation_params)
        format.html { redirect_to habitation_url(@habitation), notice: "Habitation was successfully updated." }
        format.json { render :show, status: :ok, location: @habitation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @habitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /habitations/1 or /habitations/1.json
  def destroy
    @habitation.destroy

    respond_to do |format|
      format.html { redirect_to habitations_url, notice: "Habitation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_habitation
      @habitation = Habitation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def habitation_params
      params.require(:habitation).permit(:type, :airc, :private_bat)
    end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]

  # GET /hotels or /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1 or /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels or /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1 or /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1 or /hotels/1.json
  def destroy
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:name, :adress, :num_room)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:number_pax, :numbre_hab, :id_hotel, :id_habitation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habitations_helper.rb
module HabitationsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/habitations/_form.html.erb
<%= form_with(model: habitation) do |form| %>
  <% if habitation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(habitation.errors.count, "error") %> prohibited this habitation from being saved:</h2>

      <ul>
        <% habitation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type %>
  </div>

  <div>
    <%= form.label :airc, style: "display: block" %>
    <%= form.check_box :airc %>
  </div>

  <div>
    <%= form.label :private_bat, style: "display: block" %>
    <%= form.check_box :private_bat %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/habitations/_habitation.html.erb
<div id="<%= dom_id habitation %>">
  <p>
    <strong>Type:</strong>
    <%= habitation.type %>
  </p>

  <p>
    <strong>Airc:</strong>
    <%= habitation.airc %>
  </p>

  <p>
    <strong>Private bat:</strong>
    <%= habitation.private_bat %>
  </p>

</div>

app/views/habitations/edit.html.erb
<h1>Editing habitation</h1>

<%= render "form", habitation: @habitation %>

<br>

<div>
  <%= link_to "Show this habitation", @habitation %> |
  <%= link_to "Back to habitations", habitations_path %>
</div>

app/views/habitations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Habitations</h1>

<div id="habitations">
  <% @habitations.each do |habitation| %>
    <%= render habitation %>
    <p>
      <%= link_to "Show this habitation", habitation %>
    </p>
  <% end %>
</div>

<%= link_to "New habitation", new_habitation_path %>

app/views/habitations/new.html.erb
<h1>New habitation</h1>

<%= render "form", habitation: @habitation %>

<br>

<div>
  <%= link_to "Back to habitations", habitations_path %>
</div>

app/views/habitations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @habitation %>

<div>
  <%= link_to "Edit this habitation", edit_habitation_path(@habitation) %> |
  <%= link_to "Back to habitations", habitations_path %>

  <%= button_to "Destroy this habitation", @habitation, method: :delete %>
</div>

app/views/hotels/_form.html.erb
<%= form_with(model: hotel) do |form| %>
  <% if hotel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% hotel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :adress, style: "display: block" %>
    <%= form.text_field :adress %>
  </div>

  <div>
    <%= form.label :num_room, style: "display: block" %>
    <%= form.number_field :num_room %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hotels/_hotel.html.erb
<div id="<%= dom_id hotel %>">
  <p>
    <strong>Name:</strong>
    <%= hotel.name %>
  </p>

  <p>
    <strong>Adress:</strong>
    <%= hotel.adress %>
  </p>

  <p>
    <strong>Num room:</strong>
    <%= hotel.num_room %>
  </p>

</div>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Show this hotel", @hotel %> |
  <%= link_to "Back to hotels", hotels_path %>
</div>

app/views/hotels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hotels</h1>

<div id="hotels">
  <% @hotels.each do |hotel| %>
    <%= render hotel %>
    <p>
      <%= link_to "Show this hotel", hotel %>
    </p>
  <% end %>
</div>

<%= link_to "New hotel", new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Back to hotels", hotels_path %>
</div>

app/views/hotels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hotel %>

<div>
  <%= link_to "Edit this hotel", edit_hotel_path(@hotel) %> |
  <%= link_to "Back to hotels", hotels_path %>

  <%= button_to "Destroy this hotel", @hotel, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MotorReservas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :number_pax, style: "display: block" %>
    <%= form.number_field :number_pax %>
  </div>

  <div>
    <%= form.label :numbre_hab, style: "display: block" %>
    <%= form.number_field :numbre_hab %>
  </div>

  <div>
    <%= form.label :id_hotel, style: "display: block" %>
    <%= form.number_field :id_hotel %>
  </div>

  <div>
    <%= form.label :id_habitation, style: "display: block" %>
    <%= form.number_field :id_habitation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong>Number pax:</strong>
    <%= room.number_pax %>
  </p>

  <p>
    <strong>Numbre hab:</strong>
    <%= room.numbre_hab %>
  </p>

  <p>
    <strong>Id hotel:</strong>
    <%= room.id_hotel %>
  </p>

  <p>
    <strong>Id habitation:</strong>
    <%= room.id_habitation %>
  </p>

</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rooms</h1>

<div id="rooms">
  <% @rooms.each do |room| %>
    <%= render room %>
    <p>
      <%= link_to "Show this room", room %>
    </p>
  <% end %>
</div>

<%= link_to "New room", new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>